version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4000:80"  #host port:container port
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: mysql:5.7
    ports:
      -   "3307:3306"
    environment:
      #MYSQL_USER: root
      #MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
      #MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_DATABASE: fordocker2
    networks:
      - my-network

networks:
  my-network:
