version: '3'
services:
  web:
    build:
     context: .
     Dockerfile: dockerfile
    Port:
      - "80:8000"
    depends_on:
      - database
    network:
      - my-network


  Database:
    image: mysql:5.7

    ports:
      - "3306:3306"

    environment:
      MYSQL-USER: root
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: fordocker2

    network:
      - my-network

  network:
    my-network:

